### ISSUE TITLE
File/folder name with spaces fails to show commit message.

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex-package#47]
![latestCommitIssue](https://user-images.githubusercontent.com/65342122/87806635-d0056f00-c874-11ea-9a6c-4e36b0d7c4ff.PNG)

**Comment by neel1996** [comment]
The fix has already been addressed for the issue in commit - https://github.com/neel1996/gitconvex-package/commit/d118a42a47a7e5876ce938f6c532978c906e8f77

**Comment by Nageswari-droid** [comment]
Wrong bug, mistakenly raised.
